1x2uR<script setup lang="ts">
import screenshotSelector from '@/assets/img/screenshot_selector.png'
import screenshotSelectorConfigOpen from '@/assets/img/screenshot_selector_config_open.png'
import screenshotControllerSweden from '@/assets/img/screenshot_controller_sweden.png'
import remoteRGBCodeURL from '@/assets/src/remote_rgb.txt'
import CardContainer from '@/components/Container/CardContainer.vue'
</script>

<template>
  <div class="about-view">
    <CardContainer>
      <template #header>About this tool</template>

      <p>
        Hey there! 👋
      </p>

      <p>
        This is a small application that allows you to control the RGB matrix of
        your QMK-enabled keyboard on-the-fly directly in your browser. You don't
        need to install anything on your PC other than a browser that supports
        WebHID like Chrome or Edge. Your keyboard firmware needs a bit of extra
        code, though.
      </p>
      <br />


      <details>
        <summary><strong>Disclaimer</strong></summary>
        <p>
          This project exists solely because I wanted to learn how to use some
          technologies like VueJS and WebHID, and this seemed like a fun little
          project to apply them together, so don't expect much out of it. In
          principle, I only cared to make it work with my Moonlander Mark I
          keyboard. However, since the QMK firmware repository already defines
          the keyboard matrix (that is, the physical layout of each key) for
          most of its supported keyboards, it should be easy to use this
          software with any other QMK-enabled keyboard that supports RGB matrix
          and that includes the HID message handler that responds to the HID
          messages generated by the browser --- see details about this below.
        </p>
      </details>
      <br />


      <details>
        <summary><strong>Screenshots</strong></summary>

        <p>
          <span>Listing paired devices:</span>
          <br />
          <img :src="screenshotSelector">
        </p>

        <p>
          <span>Keyboard configuration:</span>
          <br />
          <img :src="screenshotSelectorConfigOpen">
        </p>

        <p>
          <span>Keyboard RGB controller:</span>
          <br />
          <img :src="screenshotControllerSweden">
        </p>

      </details>
      <br />


      <details>
        <summary><strong>Supported keyboards</strong></summary>
        <p>
          I am only adding support for a few hand-picked keyboards that I can test
          myself in this initial version:
        </p>

        <ul>
          <li>ZSA Moonlander Mark I</li>
          <li>ZSA Planck (ortho_4x12, 1x2uC, 1x2uL and 1x2uR variants)</li>
        </ul>

        <p>
          If yours is not one of them, please open an issue in GitHub and I will
          add it!
        </p>
      </details>
      <br />

      <details>
        <summary><strong>Keyboard variants and interfaces</strong></summary>
        <p>
          <strong>Keyboard variants:</strong>
          Some keyboard models have more than one variant. For instance, by
          having larger keys for the space bar and such. If there's more than
          one variant for your keyboard, you will need to select it manually.
        </p>
        <p>
          <strong>HID interfaces:</strong>
          When enabling RAW HID in your QMK keyboard, some of you might notice
          that some keyboards expose more than one HID interface. In some cases,
          we can tell which one to use and select that by default. In other
          cases you might need to select it manually, which involves a bit of
          trial and error.
        </p>
        <p>
          After you selected both your keyboard variant and HID interface and
          pressed the "connect" button, the tool automatically saves this to
          local storage, so you only need to worry about this once.
        </p>

      </details>
      <br />


      <details>
        <summary><strong>Communication protocol</strong></summary>
        <p>
          For now, the tool implements a very simple communication protocol:
        </p>

        <ol>
          <li>
            When connecting to the keyboard, we send the REMOTE_RGB_START
            message to tell the keyboard to enter the REMOTE_RGB mode.
          </li>
          <li>
            When clicking on a color (either from the palette or from the color
            picker), we send the REMOTE_RGB_SET_COLOR message to tell the
            keyboard to change the color of the keys currently selected in the
            tool's interface to the color we just picked.
            <br />

            NOTE: since the HID message size supported by QMK is (as far as I
            know) 32bytes, we first need to split the selected keys into as
            messages as needed to tell the keyboard to repaint all the selected
            keys. Each individual messages communicates up to 12 keys to be
            repainted at a time. You don't need to care about this, though, it
            all happens under the hood.
          </li>
          <li>
            When disconnecting the keyboard, we send the REMOTE_RGB_STOP
            message to tell the keyboard to leave the REMOTE_RGB mode.
          </li>
        </ol>

        <p>
          In case you're interested, here is the shape of each kind of message:
        </p>

        <strong>REMOTE_RGB_START</strong>
        <table>
          <thead>
            <tr>
              <th>Byte</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>0</td>
              <td>Message kind (REMOTE_RGB_START)</td>
            </tr>
            <tr>
              <td>1-31</td>
              <td>Unused</td>
            </tr>
          </tbody>
        </table>
        <br />

        <strong>REMOTE_RGB_STOP</strong>
        <table>
          <thead>
            <tr>
              <th>Byte</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>0</td>
              <td>Message kind (REMOTE_RGB_STOP)</td>
            </tr>
            <tr>
              <td>1-31</td>
              <td>Unused</td>
            </tr>
          </tbody>
        </table>
        <br />

        <strong>REMOTE_RGB_SET_COLOR</strong>
        <table>
          <thead>
            <tr>
              <th>Byte</th>
              <th>Description</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>0</td>
              <td>Message kind (REMOTE_RGB_SET_COLOR)</td>
            </tr>
            <tr>
              <td>1</td>
              <td>R value</td>
            </tr>
            <tr>
              <td>2</td>
              <td>G value</td>
            </tr>
            <tr>
              <td>3</td>
              <td>B value</td>
            </tr>
            <tr>
              <td>4</td>
              <td>LED update count (1 to 12)</td>
            </tr>
            <tr>
              <td>5-7</td>
              <td>Unused for now</td>
            </tr>
            <tr>
              <td>8-9</td>
              <td>LED 1 row/column index</td>
            </tr>
            <tr>
              <td>10-11</td>
              <td>LED 2 row/column index</td>
            </tr>
            <tr>
              <td>...</td>
              <td>...</td>
            </tr>
            <tr>
              <td>30-31</td>
              <td>LED 12 row/column index</td>
            </tr>
          </tbody>
        </table>

      </details>
      <br />


      <details>
        <summary><strong>Just show me the keyboard code already</strong></summary>

        <p>Sure, here you go:</p>

        <p>
          <b>In <i>rules.mk</i>, add:</b>
          <br />
          <code>
            RAW_ENABLE = yes
          </code>
        </p>

        <p>
          <b>In <i>keymap.c</i>, add <a :href="remoteRGBCodeURL">this snippet</a></b>
        </p>
      </details>


    </CardContainer>
  </div>
</template>

<style scoped>
details[open]>summary {
  margin-bottom: 1em;
}

details>summary>strong {
  color: var(--primary);
}

details>summary>strong:hover {
  color: var(--primary-hover);
}

ul,
ol {
  margin-left: 1em;
}

details {
  border-bottom: none;
}
</style>